version: 2

sources:
  - name: raw
    database: country_database
    schema: raw_country_schema
    tables:
      - name: country_data
        columns: 
        - name: country_name
          tests:
          - not_null: true
          - unique: true
        - name: country_code
          tests:
          - not_null: true

