name: Code Linting

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.5'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 isort
        # pip install -r requirements.txt
      
    - name: Sort imports with isort
      run: |
        isort scripts dags  --check --diff

    - name: Lint with flake8
      run: |
        flake8 scripts dags  --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 scripts dags  --count --exit-zero --max-complexity=10 --max-line-length=120 --statistics
